Repository serokell/serokell-util, pull requests merged in 2018-02, with the labels that each got.

#47 Add 'NamedFieldPuns' to stylish-haskell
  .stylish-haskell.yaml
Labels: style-guide

#42 Modernize style-guide
  serokell-style.md
Labels: documentation, style-guide

#53 Bump up 'universum'
  CHANGES.md
  serokell-util.cabal
  src/Serokell/Util/Group.hs
  stack-8.0.2.yaml
  stack.yaml
Labels: refactoring

#55 [#54] Change return type of formatting funcs to Text
  CHANGES.md
  serokell-util.cabal
  src/Serokell/Util/Verify.hs
Labels: refactoring

#56 [#45] Remove Aeson.Options module, use aeson-options
  CHANGES.md
  serokell-util.cabal
  src/Serokell/Aeson/Options.hs
  src/Serokell/Util/I18N.hs
  stack-8.0.2.yaml
  stack.yaml
Labels: moving-out

#52 [SRK-91] Optimizing dependencies in serokell-util
  CHANGES.md
  serokell-util.cabal
  src/Serokell/Util/Base.hs
  src/Serokell/Util/OptParse.hs
Labels: dependency, refactoring

#58 [#32] Get rid of show and show' functions
  CHANGES.md
  serokell-util.cabal
  src/Serokell/Data/Variant/Serialization.hs
  src/Serokell/Util/Text.hs
  test/Test.hs
  test/Test/Serokell/Data/Memory/UnitsSpec.hs
  test/Test/Serokell/Data/Variant/VariantSpec.hs
  test/Test/Serokell/Util/ByteStringSpec.hs
  test/Test/Serokell/Util/CommonSpec.hs
  test/Test/Serokell/Util/TextSpec.hs
  test/Test/Serokell/Util/VerifySpec.hs
Labels: refactoring

#59 Apply hlint on the project
  serokell-util.cabal
  src/Serokell/Arbitrary.hs
  src/Serokell/Data/Variant/Class.hs
  src/Serokell/Data/Variant/Serialization.hs
  src/Serokell/Data/Variant/Variant.hs
  src/Serokell/Util/Common.hs
  src/Serokell/Util/Parse/Base64.hs
  src/Serokell/Util/Parse/Common.hs
  src/Serokell/Util/Parse/Network.hs
  src/Serokell/Util/Text.hs
  src/Serokell/Util/Verify.hs
  test/Test/Serokell/Data/Memory/UnitsSpec.hs
  test/Test/Serokell/Data/Variant/VariantSpec.hs
  test/Test/Serokell/Util/ByteStringSpec.hs
  test/Test/Serokell/Util/CommonSpec.hs
  test/Test/Serokell/Util/TextSpec.hs
Labels: refactoring
